version: "3.9"

services:
  app:
    image: pytorch/pytorch:latest  # Replace with TensorFlow/Keras image if needed
    container_name: app
    command: >
      sh -c "pip install --upgrade pip &&
             pip install -r requirements.txt &&
             tail -f /dev/null"
    volumes:
      - ../ai-rag-system:/app # Mount the project directory
    working_dir: /app
    ports:
      - "5000:5000"  # For serving models
    environment:
      - HUGGINGFACE_HUB_API_TOKEN=${HUGGINGFACE_HUB_API_TOKEN}
      - CLEARML_API_HOST=http://clearml:8008
      - CLEARML_WEB_HOST=http://clearml:8080
      - CLEARML_FILES_HOST=http://clearml:8081
    depends_on:
      - mongodb
      - qdrant
      - clearml

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  clearml:
    image: allegroai/clearml:latest
    container_name: clearml
    ports:
      - "8008:8008"  # API Server
      - "8080:8080"  # Web UI
      - "8081:8081"  # File server
    environment:
      - CLEARML_SERVER__API__HOST=http://0.0.0.0:8008
      - CLEARML_SERVER__WEB__HOST=http://0.0.0.0:8080
      - CLEARML_SERVER__FILES__HOST=http://0.0.0.0:8081
    volumes:
      - clearml_data:/clearml/data
      - clearml_logs:/clearml/logs

volumes:
  mongodb_data:
  qdrant_storage:
  clearml_data:
  clearml_logs:
